package J;

public class Day13 {
    //OOPS (OBJECT ORIENTED PROGRAMMING) - FOR GREAT EFFICIENCY ,READABILITY WE USE OOPS
    //OOPS IS NOT VERY VERY COMPULSORY, WE CAN DO IT WITHOUT OOPS
    //IT IS 4 TYPES - ENCAPSULATION, ABSTRACTION, POLYMORPHISM, INHERITENCE
    //OBJECT -ANY REAL WORLD OBJECT , OBJECT WHICH HAS ATTRIBUTES/PROPERTIES AND FUNCTIONALITY
    //CLASS IS A BLUPRINT IN WHICH OBJECT IS GENERATED.
    //PEN IS A CLASS , WE CAN WRITE, CLOSECAP,OPENCAP IS A FUNCTIONALITY , COLOUR,COMPANY IS A PROPERTY
    public static void main(String[] args) {

    }
}
